services:
    php:
        container_name: bin-github-actions-matrix
        build:
            context: .
            target: bin-github-actions-matrix
        volumes:
            - .:/project
        command: [ "tail", "-f", "/dev/null" ]
        stdin_open: true   # per tenere aperto lo stdin
        tty: true          # per abilitare il TTY
