name: PHPunit

on: [ push ]

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name.
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    phpunit:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                # When you change a version here, change it also in the SonarCloud if condition
                php: [ '8.3' ]
                symfony: [ '~6.4', '~7.2' ]

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    # Disable shallow clone
                    # https://stackoverflow.com/a/62500400/1399706
                    fetch-depth: 0

            -   name: Setup PHP
                uses: shivammathur/setup-php@2.33.0
                with:
                    php-version: ${{ matrix.php }}
                    coverage: pcov

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: |
                    echo "::set-output name=dir::$(composer config cache-files-dir)"

            -   name: Cache Composer's dependencies
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: php-composer-dependencies-cache

            -   name: Fix Symfony version
                run: |
                    composer req symfony/flex --no-update
                    composer config extra.symfony.require "${{ matrix.symfony }}"
                    composer config --no-plugins allow-plugins.symfony/flex true

            -   name: Install Composer deps
                uses: ramsey/composer-install@v2
                with:
                    composer-options: --no-scripts

            -   name: Update Composer deps (with Flex)
                # The second update is to make Flex able to do its job
                run: |
                    composer update --no-interaction --no-scripts

            -   name: Install Composer bin PHPUnit
                uses: ramsey/composer-install@v2
                with:
                    working-directory: './vendor-bin/phpunit'

            -   name: Run PHPUnit
                run: |
                    ./vendor-bin/phpunit/vendor/bin/phpunit --coverage-clover var/coverage/clover.xml --log-junit junit.xml

            - name: Upload test results to Codecov
              if: ${{ !cancelled() }}
              uses: codecov/test-results-action@v1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  flags: ${{matrix.symfony}},${{matrix.php}}

            -   name: Upload coverage reports to Codecov
                if: |
                    matrix.php == '8.3' && matrix.symfony == '~7.2' && contains(github.ref, 'dependabot') == false
                uses: codecov/codecov-action@v5
                env:
                    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
                with:
                    fail_ci_if_error: false
                    verbose: true
                    files: ./var/coverage/clover.xml

            -   name: Change paths in clover.xml
                run: |
                    sed -i 's+/home/runner/work/component-array-writer/component-array-writer+/github/workspace+g' ./var/coverage/clover.xml

            -   name: Sonarcloud
                if: |
                    matrix.php == '8.3' && matrix.symfony == '~7.2' && github.ref == 'refs/heads/dev'
                uses: SonarSource/sonarqube-scan-action@v5.1.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
